version: '3.8'
services:
  zookeeper:
    ports:
      - 22181:2181
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:7.4.4
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - kafka-network
  kafka-1:
    image: confluentinc/cp-kafka:7.4.4
    container_name: kafka-1
    ports:
      - 29092:29092
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - kafka-network
#  kafka-ui:
#    image: provectuslabs/kafka-ui:latest
#    container_name: ui
#    ports:
#      - 8080:8080
#    depends_on:
#      - kafka-1
#    environment:
#      KAFKA_CLUSTERS_0_NAME: local
#      KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS: kafka:29092
#    networks:
#      - kafka-network
networks:
  kafka-network:
    driver: bridge