@startuml

autonumber

actor Клиент as Client
boundary Handler
control BusinessLogic
entity PostgresSaver
actor Postgres
boundary SMSSender
boundary EmailSender

activate Client
Client -> Handler: Создать новый элемент
activate Handler
Handler -> Handler: Преобразование во\nвнутренний формат
Handler -> BusinessLogic: Создать новый элемент
activate BusinessLogic
BusinessLogic -> PostgresSaver: Сохранить событие в базу
activate PostgresSaver
PostgresSaver -> Postgres: Сохранить событие в базу
activate Postgres
Postgres --> PostgresSaver: OK
deactivate Postgres
PostgresSaver --> BusinessLogic: OK
deactivate PostgresSaver
par Параллельное выполнение
BusinessLogic -> SMSSender: Отправить сообщение заинтересованным лицам по СМС
BusinessLogic -> EmailSender: Отправить сообщение заинтересованным лицам по Email
end
BusinessLogic --> Handler: Успешно обработано
deactivate BusinessLogic
Handler --> Client: Успешно обработано
deactivate Handler
@enduml