security.protocol=SASL_PLAINTEXT
sasl.mechanism=PLAIN
sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="admin" password="admin-secret";
ssl.truststore.location=/etc/kafka/secrets/kafka.truststore.jks
ssl.truststore.password=password
ssl.keystore.location=/etc/kafka/secrets/kafka.keystore.jks
ssl.keystore.password=password
ssl.key.password=password